bot:
  name: Nobita
  gender: Male
  boss: Gaurav
  voice_engine: pyttsx3
  voice_reply: True

default:
  name: Gaurav
  age: 21

interaction_setting:
  voice_reply: False
  text_reply: True
  voice_read_voice_reply: False
  text_read: True

template_path:
  cpp: $DEFAULT
  python: $DEFAULT

compiler:
  cpp: g++ -O2 -Wshift-overflow=2  -Wshadow  '{filename}' -o '{executable}' && ./'{executable}'
  cpp_debug: g++ -std=c++17 -Wshadow -Wconversion -Wall -DPAUL -DLOCAL -Wshift-overflow=2 -Wshadow -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC  -g '{filename}' -o '{executable}' && ./'{executable}'
  python: python3 '{filename}'

developer:
  debug: False
  learn: True

start_time:
  first_time: True

