bot:
  boss: Saurabh
  gender: Male
  name: Nobita
  voice_engine: pyttsx3
  voice_reply: true
browser:
  browser_name: chrome
compiler:
  cpp: g++ -O2 -Wshift-overflow=2  -Wshadow  '{filename}' -o '{executable}' && ./'{executable}'
  cpp_debug: g++ -std=c++17 -Wshadow -Wconversion -Wall -DPAUL -DLOCAL -Wshift-overflow=2
    -Wshadow -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC  -g
    '{filename}' -o '{executable}' && ./'{executable}'
  python: python3 '{filename}'
credentials:
  lms:
    password: Watermelo@1232
    username: 18scse1010138
default:
  age: 21
  name: Gaurav
developer:
  debug: false
  learn: true
directories:
  assignment_attachment: C:\Users\saumyakr1232\OneDrive\Documents
interaction_setting:
  text_read: true
  text_reply: true
  voice_read_voice_reply: false
  voice_reply: false
start_time:
  first_time: false
template_path:
  cpp: $DEFAULT
  python: $DEFAULT
